apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - loki/loki-deployment.yaml
  - promtail/promtail-daemonset.yaml
  - grafana/grafana-deployment.yaml

# این بخش تنظیمات Promtail که قبلا نوشتیم را به کلاستر می‌شناساند
configMapGenerator:
  - name: promtail-config
    files:
      - promtail/config.yaml