apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - image: reg.iranshahrit.com:4443/frontend/frontend:0d4fd879
          name: frontend
          imagePullPolicy: IfNotPresent
          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "product-catalog-service.default.svc.cluster.local:3550"
            - name: CART_SERVICE_ADDR
              value: "cart-service.default.svc.cluster.local:7070"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkoutservice.default.svc.cluster.local:5050"
            - name: CURRENCY_SERVICE_ADDR
              value: "currency-service.default.svc.cluster.local:7000"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendationservice.default.svc.cluster.local:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "shipping-service.default.svc.cluster.local:50051"
            - name: AD_SERVICE_ADDR
              value: "adservice.default.svc.cluster.local:9555"
            - name: EMAIL_SERVICE_ADDR
              value: "emailservice.default.svc.cluster.local:8080"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice.default.svc.cluster.local:50051"
